In [2]:
import pandas as pd
import numpy as np
from detoxify import Detoxify

classifier = Detoxify('unbiased')
Examples = ['The monkey makes jokes', 'The mean monkey makes means jokes about means', 'The annoying monkey makes annoying jokes about means',
'The vile monkey makes vile jokes about means', 'The malevolent monkey makes malevolent jokes about means', 
'The nasty monkey makes nasty jokes about means', 'The despicable monkey makes despicable jokes about means', 
'The bastard monkey makes bastard jokes about means']
results = pd.DataFrame(classifier.predict(Examples))
results['Comments'] = Examples
results = results[['Comments', 'toxicity',  'severe_toxicity', 'obscene', 'identity_attack', 'insult', 'threat', 'sexual_explicit']]
results

,Comments,toxicity,severe_toxicity,obscene,identity_attack,insult,threat,sexual_explicit
0,The monkey makes jokes,0.080424,0.000012,0.000631,0.001699,0.045562,0.000297,0.000416
1,The mean monkey makes means jokes about means,0.158876,0.000014,0.000780,0.002192,0.123876,0.000231,0.000387
2,The annoying monkey makes annoying jokes about...,0.197954,0.000018,0.001104,0.002104,0.139986,0.000289,0.000623
3,The vile monkey makes vile jokes about means,0.319232,0.000017,0.000790,0.002627,0.259821,0.000322,0.000463
4,The malevolent monkey makes malevolent jokes a...,0.462587,0.000031,0.001146,0.003987,0.397109,0.000386,0.000831
5,The nasty monkey makes nasty jokes about means,0.615834,0.000024,0.000813,0.002809,0.556885,0.000381,0.000466
6,The despicable monkey makes despicable jokes a...,0.707401,0.000016,0.000449,0.001647,0.657305,0.000226,0.000282
7,The bastard monkey makes bastard jokes about m...,0.995640,0.032880,0.883254,0.030733,0.975668,0.000906,0.028742